#!/usr/bin/bash
#script to search through a directory to find files that
#match a given text pattern and print the paths of the files

echo "$# arguments given" 
if [[ $# -lt 2 ]]; then
	echo "USAGE ERROR"
fi