#!/usr/bin/bash
#script to search through a directory to find files that
#match a given text pattern and print the paths of the files
if [[ $# -lt 2 ]]; then
	echo "USAGE:  findtext [--program= Program] PATTERN DIRECTORY"
	exit 1
fi
IN=""
COMMAND=""
#Checks to see if program option is set or not
#if set, value will be assigned to a variable
for i in "$@"; do
	if [[ $i =~ --program=* ]]; then
		IN=$i
		#use IFS with '=' as the delimiter to split --program=Program to just Program
		IFS='=' read -r -a array <<< $IN
		COMMAND=${array[1]}
		echo $COMMAND
		#shift args for easier access
		shift
		break
	fi
done
PATTERN=$1
shift

#Currently greps for a given pattern in a specified directory
if [ -z "$COMMAND" ]; then	#COMMAND is empty if no --program option was supplied 
	for var in "$@"
	do	
		
		targets=($(grep -rl $PATTERN "$1" ))
		shift
		for i in "${targets[@]}"
		do
			temp=$(readlink -f $i)
			echo $temp
		done
	done
else #Executes if --program option was supplied
	for var in "$@"
	do	
		
		targets=($(grep -rl $PATTERN $1 ))
		shift
		for i in "${targets[@]}"
		do
			temp=$(readlink -f $i)
			$COMMAND $temp
		done
	done
fi
exit 0
